package me.scraplesh.hotsdraft.domain.heroes

enum class Hero(val role: Role, val universe: Universe, val difficulty: HeroDifficulty) {
    Abathur(
      Role.Support,
      Universe.Starcraft,
      HeroDifficulty.VeryHard
    ),
    Alarak(
      Role.MeleeAssassin,
      Universe.Starcraft,
      HeroDifficulty.Hard
    ),
    Alexstrasza(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Ana(
      Role.Healer,
      Universe.Overwatch,
      HeroDifficulty.Hard
    ),
    Anduin(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Anubarak(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Artanis(
      Role.Bruiser,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Arthas(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Auriel(
      Role.Healer,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Azmodan(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Blaze(
      Role.Tank,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Brightwing(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Cassia(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Chen(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Cho(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Chromie(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Deathwing(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Deckard(
      Role.Healer,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Dehaka(
      Role.Bruiser,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Diablo(
      Role.Tank,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    DiVa(
      Role.Bruiser,
      Universe.Overwatch,
      HeroDifficulty.Medium
    ),
    ETC(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Falstad(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Fenix(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Gall(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Garrosh(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Gazlowe(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Genji(
      Role.RangedAssassin,
      Universe.Overwatch,
      HeroDifficulty.Hard
    ),
    Greymane(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Guldan(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Hanzo(
      Role.RangedAssassin,
      Universe.Overwatch,
      HeroDifficulty.Medium
    ),
    Illidan(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Imperius(
      Role.Bruiser,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Jaina(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Johanna(
      Role.Tank,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Junkrat(
      Role.RangedAssassin,
      Universe.Overwatch,
      HeroDifficulty.Medium
    ),
    Kaelthas(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    KelThuzad(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Kerrigan(
      Role.MeleeAssassin,
      Universe.Starcraft,
      HeroDifficulty.Hard
    ),
    Kharazim(
      Role.Healer,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Leoric(
      Role.Bruiser,
      Universe.Diablo,
      HeroDifficulty.Easy
    ),
    LiLi(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    LiMing(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    LtMorales(
      Role.Healer,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Lucio(
      Role.Healer,
      Universe.Overwatch,
      HeroDifficulty.Medium
    ),
    Lunara(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Maiev(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Malfurion(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    MalGanis(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Malthael(
      Role.Bruiser,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Medivh(
      Role.Support,
      Universe.Warcraft,
      HeroDifficulty.VeryHard
    ),
    Mephisto(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Muradin(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Murky(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Nazeebo(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Nova(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Orphea(
      Role.RangedAssassin,
      Universe.Nexus,
      HeroDifficulty.Medium
    ),
    Probius(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Hard
    ),
    Qhira(
      Role.MeleeAssassin,
      Universe.Nexus,
      HeroDifficulty.Medium
    ),
    Ragnaros(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Raynor(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Easy
    ),
    Rehgar(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Rexxar(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Samuro(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    SgtHammer(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Hard
    ),
    Sonya(
      Role.Bruiser,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Stitches(
      Role.Tank,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Stukov(
      Role.Healer,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Sylvanas(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Tassadar(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    TheButcher(
      Role.MeleeAssassin,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    TheLostVikings(
      Role.Support,
      Universe.Nexus,
      HeroDifficulty.VeryHard
    ),
    Thrall(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Tracer(
      Role.RangedAssassin,
      Universe.Overwatch,
      HeroDifficulty.Hard
    ),
    Tychus(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Tyrael(
      Role.Tank,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Tyrande(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Uther(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Easy
    ),
    Valeera(
      Role.MeleeAssassin,
      Universe.Warcraft,
      HeroDifficulty.Hard
    ),
    Valla(
      Role.RangedAssassin,
      Universe.Diablo,
      HeroDifficulty.Easy
    ),
    Varian(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Whitemane(
      Role.Healer,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Xul(
      Role.Bruiser,
      Universe.Diablo,
      HeroDifficulty.Medium
    ),
    Yrel(
      Role.Bruiser,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
    Zagara(
      Role.RangedAssassin,
      Universe.Starcraft,
      HeroDifficulty.Medium
    ),
    Zarya(
      Role.Support,
      Universe.Overwatch,
      HeroDifficulty.Easy
    ),
    Zeratul(
      Role.MeleeAssassin,
      Universe.Starcraft,
      HeroDifficulty.Hard
    ),
    Zuljin(
      Role.RangedAssassin,
      Universe.Warcraft,
      HeroDifficulty.Medium
    ),
}
